### ISSUE TITLE
Expression modification

### ISSUE THREAD

**Issue by giriarteS** [nick-youngblut/HTSSIP#22]
I want to modify the expression. 
params = get_treatment_params(A1, 'Sample')
ex= "(Sample=='${Sample}')"
test = phyloseq_subset(A1, params, ex)

I get this:
$`(Sample=='Leaf')`
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 2203 taxa and 24 samples ]
sample_data() Sample Data:       [ 24 samples by 16 sample variables ]
tax_table()   Taxonomy Table:    [ 2203 taxa by 7 taxonomic ranks ]
phy_tree()    Phylogenetic Tree: [ 2203 tips and 2202 internal nodes ]
$`(Sample=='Root')`
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 2203 taxa and 24 samples ]
sample_data() Sample Data:       [ 24 samples by 16 sample variables ]
tax_table()   Taxonomy Table:    [ 2203 taxa by 7 taxonomic ranks ]
phy_tree()    Phylogenetic Tree: [ 2203 tips and 2202 internal nodes ]

How the expression should be modified to get the output below
$Leaf
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 2203 taxa and 24 samples ]
sample_data() Sample Data:       [ 24 samples by 16 sample variables ]
tax_table()   Taxonomy Table:    [ 2203 taxa by 7 taxonomic ranks ]
phy_tree()    Phylogenetic Tree: [ 2203 tips and 2202 internal nodes ]
$Root
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 2203 taxa and 24 samples ]
sample_data() Sample Data:       [ 24 samples by 16 sample variables ]
tax_table()   Taxonomy Table:    [ 2203 taxa by 7 taxonomic ranks ]
phy_tree()    Phylogenetic Tree: [ 2203 tips and 2202 internal nodes ]

**Comment by seb369** [comment]
It looks like you are trying to change the names of the phyloseq objects in your list. Currently phyloseq_subset() is using the format of the "ex" variable (Sample=='${Sample}') to do the subsetting. The function then simply uses that same string for list object names. For your data, one quick fix would be to change the names of the objects in your list once the list is created.  To do that you can run the following:

params = get_treatment_params(A1, 'Sample')
ex= "(Sample=='${Sample}')"
test = phyloseq_subset(A1, params, ex)
names(test) = c(“Leaf”, “Root”)

The function "names(test)" will change the list object names.
